SELECT P.EMP_FNAME, P.EMP_LNAME
FROM PILOTDIM P INNER JOIN FACTTABLE F ON P.PILOT_KEY = F.PILOT_KEY
WHERE CHAR_DISTANCE = (SELECT MAX(CHAR_DISTANCE) FROM FACTTABLE)
GROUP BY P.EMP_FNAME, P.EMP_LNAME

SELECT A.MOD_CODE, MONTH(T.CHAR_DATE) AS [MONTH], SUM(F.REVENUE) AS [TOTAL REVENUE]
FROM  FACTTABLE F INNER JOIN AIRCRAFTDIM A ON F.AIRCRAFT_KEY = A.AIRCRAFT_KEY
	  INNER JOIN TIMEDIM T ON F.TIME_KEY = T.TIME_KEY
GROUP BY A.MOD_CODE, MONTH(T.CHAR_DATE)
ORDER BY SUM(F.REVENUE) ASC