USE CIS31073



CREATE TABLE PILOTDIM
(
PILOT_KEY INT IDENTITY(1,1) NOT NULL,
EMP_NUM INT NOT NULL,
EMP_LNAME VARCHAR(25),
EMP_FNAME VARCHAR(25),
PIL_LICENSE VARCHAR(5),
PIL_RATINGS VARCHAR(25)
)

CREATE TABLE AIRCRAFTDIM
(
AIRCRAFT_KEY INT IDENTITY(1,1) NOT NULL,
MOD_CODE VARCHAR(10) NOT NULL,
AC_NUMBER VARCHAR(15),
AC_TTAF VARCHAR(25),
AC_TTEL VARCHAR(25),
AC_TTER VARCHAR(25)
)

CREATE TABLE TIMEDIM
(
TIME_KEY INT IDENTITY(1,1) NOT NULL,
CHAR_DATE DATETIME,
CHAR_MONTH INT,
CHAR_YEAR INT
)


CREATE TABLE FACTTABLE
(

PILOT_KEY	    INT NOT NULL,
AIRCRAFT_KEY	    INT NOT NULL,
TIME_KEY		INT NOT NULL,
CHAR_DISTANCE	       FLOAT,
CHAR_FUEL_GALLONS	   FLOAT,
MOD_CHANGE_MILEOIL	   FLOAT
)


DROP TABLE PILOTDIM
DROP TABLE AIRCRAFTDIM
DROP TABLE TIMEDIM
DROP TABLE FACTTABLE


CREATE TABLE STAGING 
(
PILOT_KEY INT,
EMP_NUM INT,
EMP_FNAME VARCHAR(10),
EMP_LNAME VARCHAR(10),
AIRCRAFT_KEY INT,
MOD_CODE VARCHAR(10),
TIME_KEY INT,
CHAR_DATE DATETIME,
CHAR_FUEL_GALLONS FLOAT(8),
CHAR_DISTANCE FLOAT(8),
MOD_CHG_MILE FLOAT
)

DROP TABLE STAGING


ALTER TABLE PILOTDIM
ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (PILOT_KEY)

ALTER TABLE AIRCRAFTDIM
ADD CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AIRCRAFT_KEY)

ALTER TABLE TIMEDIM
ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TIME_KEY)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_PILOTDIM FOREIGN KEY (PILOT_KEY) REFERENCES PILOTDIM(PILOT_KEY)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_AIRCRAFTDIM FOREIGN KEY (AIRCRAFT_KEY) REFERENCES AIRCRAFTDIM(AIRCRAFT_KEY)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TIME_KEY) REFERENCES TIMEDIM(TIME_KEY)


ALTER TABLE FACTTABLE
ADD PRIMARY KEY (PILOT_KEY, AIRCRAFT_KEY, TIME_KEY)
